basePath: /
definitions:
  github_com_arfan21_project-sprint-social-media-api_internal_model.FriendRequest:
    properties:
      userId:
        type: string
    required:
    - userId
    type: object
  github_com_arfan21_project-sprint-social-media-api_internal_model.PostRequest:
    properties:
      postInHtml:
        minLength: 3
        type: string
      tags:
        items:
          type: string
        type: array
    required:
    - postInHtml
    - tags
    type: object
  github_com_arfan21_project-sprint-social-media-api_internal_model.UserLoginRequest:
    properties:
      credentialType:
        enum:
        - phone
        - email
        type: string
      credentialValue:
        type: string
      password:
        maxLength: 15
        minLength: 5
        type: string
    required:
    - credentialType
    - credentialValue
    - password
    type: object
  github_com_arfan21_project-sprint-social-media-api_internal_model.UserLoginResponse:
    properties:
      accessToken:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  github_com_arfan21_project-sprint-social-media-api_internal_model.UserRegisterRequest:
    properties:
      credentialType:
        enum:
        - phone
        - email
        type: string
      credentialValue:
        type: string
      name:
        maxLength: 50
        minLength: 5
        type: string
      password:
        maxLength: 15
        minLength: 5
        type: string
    required:
    - credentialType
    - credentialValue
    - name
    - password
    type: object
  github_com_arfan21_project-sprint-social-media-api_internal_model.UserResponse:
    properties:
      createdAt:
        type: string
      friendCount:
        type: integer
      imageUrl:
        type: string
      name:
        type: string
      userId:
        type: string
    type: object
  github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.ErrValidationResponse:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse:
    properties:
      data: {}
      message:
        example: Success
        type: string
      meta: {}
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://www.synapsis.id
  description: This is a sample server cell for project-sprint-social-media-api.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: project-sprint-social-media-api
  version: "1.0"
paths:
  /v1/friend:
    delete:
      consumes:
      - application/json
      description: Delete friend
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payload friend request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_internal_model.FriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
      summary: Delete friend
      tags:
      - friend
    get:
      consumes:
      - application/json
      description: Get list user
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Limit data
        in: query
        name: limit
        type: integer
      - description: Offset data
        in: query
        name: offset
        type: integer
      - description: Search data
        in: query
        name: search
        type: string
      - description: Sort by data
        in: query
        name: sortBy
        type: string
      - description: Order by data
        in: query
        name: orderBy
        type: string
      - description: Only friend data
        in: query
        name: onlyFriend
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_internal_model.UserResponse'
                  type: array
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
      summary: Get list user
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Add friend
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payload friend request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_internal_model.FriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
      summary: Add friend
      tags:
      - friend
  /v1/image:
    post:
      consumes:
      - multipart/form-data
      description: Upload image to s3
      parameters:
      - description: Image file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
      summary: Upload Image
      tags:
      - Image Uploader
  /v1/post:
    post:
      consumes:
      - application/json
      description: Create post
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payload post request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_internal_model.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
      summary: Create post
      tags:
      - post
  /v1/user/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: Payload user Login Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_internal_model.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_internal_model.UserLoginResponse'
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
      summary: Login user
      tags:
      - user
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: Payload user Register Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_internal_model.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_internal_model.UserLoginResponse'
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-social-media-api_pkg_pkgutil.HTTPResponse'
      summary: Register user
      tags:
      - user
swagger: "2.0"
